version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.2
    environment:
      POSTGRES_DB: "lucid"
      POSTGRES_USER: "lucid"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:6.7
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - postgres

  cache:
    container_name: redis_container
    image: redis:6.2-alpine
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

# networks:
#   postgres:
#     driver: bridge

volumes:
  cache:
    driver: local
